### ISSUE TITLE
'nil' requires a contextual type

### ISSUE THREAD

**Issue by anatoljevich** [joemasilotti/daily-log#13]
I'm getting 'nil' requires a contextual type error when trying to build the project. How to fix it?

Xcode 14.3.1, Swift 5.8.1

<img width="755" alt="Снимок экрана 2024-03-27 в 15 45 38" src="https://github.com/joemasilotti/daily-log/assets/417408/ae815359-946b-40e1-9168-a82f1ea45201">

**Comment by joemasilotti** [comment]
It looks like you need explicit `return` calls for each of the cases.

**Comment by anatoljevich** [comment]
I changed TurboNavigator.swift to 

```
    private func controller(for proposal: VisitProposal) -> UIViewController? {
        switch delegate.handle(proposal: proposal) {
        case .accept:
            return Turbo.config.defaultViewController(proposal.url)
        case .acceptCustom(let customViewController):
            return customViewController
        case .reject:
            return nil
        }
    }
```

and TurboNavigationHierarchyController.swift to 

```
    func navController(for navigationType: NavigationStackType) -> UINavigationController {
        switch navigationType {
        case .main: return navigationController
        case .modal: return modalNavigationController
        }
    }
```

and after that was able to build
