### ISSUE TITLE
»Recent entries" for water are NOT unique

### ISSUE THREAD

**Issue by janraasch** [joemasilotti/daily-log#7]
Hi (again) 😁😇,

while working on #2 / #6 I realised that the `distinct(:amount)`-call in `WaterEntry`

https://github.com/joemasilotti/daily-log/blob/510e142358fa49d1470826f7c38ed17be396ebf4/rails/app/models/water_entry.rb#L8 

does not actually do anything. Here's a link to the documentation: https://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-distinct. The method signature of `distinct` is very misleading I think 😅.

# How to reproduce 

Add a couple of `WaterEntry`-items with the **same** value:

<img width="843" alt="Screenshot 2023-12-21 at 13 32 59" src="https://github.com/joemasilotti/daily-log/assets/425211/1e95d567-71fe-4498-a298-13561662b0a5">

# Idea 4 a Fix

IMHO the simplest thing would be do take care of uniqueness (and sorting - #2) after loading the latest three items into the application, i.e.

```ruby
scope :recent, -> { order(created_at: :desc).limit(3).to_a.uniq(&:amount_value) }
```

or

```ruby
scope :recent, -> { order(created_at: :desc).limit(3).to_a.uniq { |wi| wi.amount.value } }
```

Then, #2 could be solved by appending `.sort_by(:amount)`.

**Comment by joemasilotti** [comment]
Ha, I should have read this first before addressing your other PR! 😆

This still won't work if the last 2 entries are the same because we are querying for 3 _before_ grabbing unique entries. 

I'm going to close this in favor of the PR you opened since that now has a failing test.
